### ISSUE TITLE
InstaParse

### ISSUE THREAD

**Issue by mceraso** [mceraso/Instaparsepath#1]
Hi Codepath, wireframe and partial completion of app are ready for review! Thank you! /cc @codepathreview

Michael

**Comment by minhchau273** [comment]
Hi Michael,

It looks like you still need to complete some required user stories for your submission to be complete. The photos cannot be shown on the timeline, right?

Your assignment needs to be updated within 24hrs in order for you to receive credit for this assignment.

Best,
Chau

**Comment by mceraso** [comment]
@codepathreview

Hi Chau, yes.. Any ideas on how I can fix this? I implemented Pod 'ParseUI' and made the cell's imageview a PFImageView. But the app crashes when it tries to populate the cells! I've got a few leads from classmates but any hints you can add will be helpful.

All best,
Michael

**Comment by mceraso** [comment]
We run this error:

Instaparsepath[19958:1363466] -[UIImageView setFile:]: unrecognized selector sent to instance 0x7f9ca1cbb7d0
2016-03-07 21:26:41.868 Instaparsepath[19958:1363466] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIImageView setFile:]: unrecognized selector sent to instance 0x7f9ca1cbb7d0'

**Comment by minhchau273** [comment]
Hi Michael,

I'm at work so I cannot figure out your issue now. But you can try this solution. When loading photo, don't use the `imageData`. You can get the image url from the `PFFile`. Then use `AFNetworking` to show the image to the `UIImageView`. I tried this and succeed 😄

Best,
Chau

**Comment by mceraso** [comment]
I got it! I had to go into main.storyboard and change the class of PhotoImageView from UIImageView to PFImageView!

**Comment by mceraso** [comment]
@codepathreview

**Comment by minhchau273** [comment]
Hi Michael,

I do not see an animated gif in your README. Please add a gif ASAP. Once you have added your gif, make sure that it actually renders (animates) within your README.

Thanks,
Chau

**Comment by mceraso** [comment]
Hi Chau,

I'm not sure what the issue. I definitely see an animated gif when I use this link: https://github.com/mceraso/Instaparsepath

Did you give it a minute to load?
How could it be that I see it on mine?

I've never had this problem before.

Michael

**Comment by minhchau273** [comment]
:+1: Congratulations on finishing the final assignment! It's impressive to realize how far you've come in the first half of the class, going from building a simple tip calculator to a full Instagram app with your own backend.

### Some small comments:
- You should set secure for the password text field.
- It'd be better if you show the alert when signing in with invalid username/password or signing up with the existing user.
- After posting a photo, your app should return to the timeline immediately instead of tapping Back button.

We hope you enjoyed the final assignment. Parse is a great service that makes building a backend app much easier. We have a detailed [Project 6 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_6_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.

From here on out there are no more assignments as the focus shifts to the final group project. You'll be working over the next several weeks to build your app idea with your team and then finishing the class with a demo day!
